### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kishanKgupta**
add new background color

### CODE REVIEW

**Comment by kishanKgupta** [comment]
ok it's good

**Review by kishanKgupta — COMMENTED** [review]
background change for body

**Comment by kishanKgupta** [comment]
> add new background color

ok bro thanks

**Comment by kishan-1000** [comment]
okk

**Comment by kishanKgupta** [comment]
actually I use new background color , and now your page is so awesome.

**Review by kishan-1000 — COMMENTED** [review]
ok I add

**Review by kishan-1000 — COMMENTED** [review]
okk

**Pull request closed without merging**
